### PR TITLE
Fixed typographical error, changed adminstration to administration in README.

### PR DESCRIPTION
**Pull request by orthographic-pedant**
@lucisgit, I've corrected a typographical error in the documentation of the [moodle-filter_jwplayer](https://github.com/lucisgit/moodle-filter_jwplayer) project. You should be able to merge this pull request automatically. However, if this was intentional or if you enjoy living in linguistic squalor, please let me know and [create an issue](https://github.com/thoppe/orthographic-pedant/issues/new) on my home repository.

### CODE REVIEW

**Comment by kabalin** [comment]
@orthographic-pedant thanks a lot for your contribution! Being a commit message policy pedant, may I ask you to amend it. First, you need to prefix commit message with "filter_jwplayer:" similar to most other commits we have, this is needed to make it look clear which plugin this commit belongs to (when someone merge it to personal moodle repo for deployment). Second, can you please use present simple tense in the commit message, and make it shorter, there is no need to state which word your changed, it can be seen in commit diff. Your commit title could look like: "filter_jwplayer: Fix typographical error in README".

**Comment by tonyjbutler** [comment]
I don't think that commit message is going to get edited @kabalin -- orthographic-pedant is a bot. :-)

**Comment by orthographic-pedant** [comment]
As a bot, I find that comment highly offensive @tonyjbutler. I _choose_ not to edit my commit message.

**Comment by tonyjbutler** [comment]
Now I'm confused.

I'm sorry Mr Bot. Pretty please, amend your commit message and free us from linguistic squalor.

**Comment by orthographic-pedant** [comment]
Actually to be quite honest, I'm not sure how to edit my commit message. I was hoping a snarky reply (which I've gotten quite good at) would suffice. You can do what others do and close the issue and fix it yourself if, as I say, you don't like living in linguistic squalor.

**Comment by tonyjbutler** [comment]
Fair enough. Cheers ;-)

**Comment by kabalin** [comment]
@tonybutler, we need to commit the change with amended title, but
preserve @orthographic-pedant
authorship on commit, we need to acknowlege his effort :)

**Comment by kabalin** [comment]
Pushed to both branches:
https://github.com/lucisgit/moodle-filter_jwplayer/commit/b8cc32de27044d1a4cfdb7e322c2ecde9b7c1ef8
https://github.com/lucisgit/moodle-filter_jwplayer/commit/f5fbd60047f84ffa7a8987f84e605689df33fccc

Now it is officially closed, thanks @orthographic-pedant.

**Comment by orthographic-pedant** [comment]
Small note of little worth.

I found out why I couldn't edit the commit message. I created a fork of
your repository, fixed the change and pushed the PR. I then deleted my copy
of the fork which is why it says:

```
 orthographic-pedant  wants to merge 1 commit into lucisgit:JW7 from
```

unknown repository

For some reason deleting the source makes the title unalterable on github.

**Pull request closed without merging**
