### PR TITLE
Google Analytics Support

### PR DESCRIPTION
**Pull request by owenbarritt**
Added support for google analytics integration for the premium version of the jwplayer.

### CODE REVIEW

**Comment by kabalin** [comment]
Hello @owenbarritt, thanks for your contribution! Can you please squash all commits into a single one and resubmit a pull requiest. Please pay particular attention to indents in lib.php, there should be no tabs or trailing spaces. Also, there a convention to start every commit message with "filter_jwplayer:" (see commits history), this is to make it look better and easier to understand which commit belongs to which part, when someone integrates plugin directly to own Moodle instance using git subtree.
Thanks a lot for your work!

**Comment by owenbarritt** [comment]
OK.
All squashed and commit message reworded as requested.

**Comment by owenbarritt** [comment]
Indents should now be fixed.

**Comment by kabalin** [comment]
Moerged, thanks a lot @owenbarritt for contributing.

**Pull request merged**
