### PR TITLE
Allow % dimensions and width-only parameters to be passed to player

### PR DESCRIPTION
**Pull request by owenbarritt**
Adds support for responsive width by allowing % values and width only dimensions to be passed to player in the url.

Also fixes the assumption that the player automatically sets the height, which appears to be false for fixed width settings or if the aspect ratio isn't set for responsive width settings.

### CODE REVIEW

**Comment by kabalin** [comment]
Looks good, @owenbarritt. Please sort all indents issues first, there are many of them.

**Comment by owenbarritt** [comment]
Sorry.  Should now be fixed.

**Comment by owenbarritt** [comment]
Are there any other issues that need addressing in this before it can be merged?

The indents should all be fixed.

**Comment by owenbarritt** [comment]
OK, typo also now corrected

**Comment by kabalin** [comment]
Merged! Thanks for contribution.

**Pull request merged**
