### PR TITLE
Embed download button setup in jwplayer init.

### PR DESCRIPTION
**Pull request by jojoob**

### CODE REVIEW

**Comment by kabalin** [comment]
Thanks @jojoob, code looks good to me. Can you change commit message title to match convention used at the moment, i.e. filter_flowplayer: Move download button setup in jwplayer init call.

**Comment by jojoob** [comment]
Notifier: @kabalin I've amended the git commit message as you suggested and force pushed the change.

**Comment by kabalin** [comment]
Thanks @jojoob for your contribution. The change is now merged.

**Comment by jojoob** [comment]
Great, it's a pleasure to contribute to your project. :)

**Pull request merged**
