### PR TITLE
filter_jwplayer:  Change custom skin support to CSS and add mpeg-dash support (task #37)

### PR DESCRIPTION
**Pull request by owenbarritt**
Resubmit of #34 rebased on JW7 branch

Addresses skins issue from task #37

### CODE REVIEW

**Comment by kabalin** [comment]
@owenbarritt I have just looked through this one. Can you please refactor it a little:
1. Move mpeg-dash patch to the separate commit (could stay in this pull request, just a separate commit).
2. Remove v6 skin support implementation completely (with XML files upload settings code) and implement v7 skins functionality only - basically we have a separate branch to JW6 which already has skins support the way it was done in v6, in JW7 let's make it work with JW Player 7 only, no need to support both versions in the same code.
Thanks!

**Comment by owenbarritt** [comment]
OK, I'll have a look when I get a moment (probably next week now)

**Comment by kabalin** [comment]
No rush at all, thanks!

**Comment by owenbarritt** [comment]
OK, now split into 2 commits with XML skin support also removed.

**Comment by kabalin** [comment]
Thanks @owenbarritt, this is now merged.

**Pull request merged**
