### PR TITLE
Log player events

### PR DESCRIPTION
**Pull request by owenbarritt**
First commit brings existing JS code inline with the JW7 API guidance at http://support.jwplayer.com/customer/portal/articles/1413074-javascript-api-quick-start

Second commit adds support for logging key player events.  It creates the events in moodle corresponding to the player events as listed in the commit message.

### CODE REVIEW

**Comment by owenbarritt** [comment]
Coding style for this one should now be fix.  Let me know if I've missed anything.

**Comment by kabalin** [comment]
@owenbarritt can you please rebase this on updated JW7 branch.

Really great feature, thanks for your time!

**Comment by owenbarritt** [comment]
OK, should be rebased now.

**Comment by kabalin** [comment]
Great, thanks a lot!

**Comment by kabalin** [comment]
@owenbarritt do you think that errors need to be recorded in activity log as well? I think browser console debug output should be sufficient for them, unless you need to "debug" remotely that player works on client side.

**Comment by owenbarritt** [comment]
Yes, as otherwise they only occur locally in the client and there's no record of any issue on the server.

If you are looking at a particular user's interaction with a video, then any errors they hit are part of this so need to be included if you are going to get a full picture.  At the end of the day they may be a big reason for a user not watching a particular video.

**Comment by kabalin** [comment]
@owenbarritt May I ask which version of Moodle are you currently using?

**Comment by owenbarritt** [comment]
We're currently using 2.9.

This might have been written on 2.7 though.

Is there an issue with this with some version of moodle?

**Comment by kabalin** [comment]
I have refactored JW7 to use AMD (https://docs.moodle.org/dev/Javascript_Modules, new thing in 2.9), it is much more flexible IMO, will release both JW6 and JW7 hopefully tomorrow or early next week. JW7 will be for Moodle 2.9+ only.

**Comment by owenbarritt** [comment]
Makes sense, it would need changing sooner or later anyway.

**Pull request merged**
