### PR TITLE
filter_jwplayer:  Add default poster image option

### PR DESCRIPTION
**Pull request by owenbarritt**
Added an option to set a sitewide default poster image

### CODE REVIEW

**Comment by kabalin** [comment]
Hi @owenbarritt, thanks for working on this commit. There are some very minor issues that need to be fixed, I have added some inline comments.

**Comment by owenbarritt** [comment]
All those should be fixed now.  Thanks.

**Comment by kabalin** [comment]
One more... see comments.

**Comment by owenbarritt** [comment]
OK, that should be done too now.  Thanks

**Comment by kabalin** [comment]
Merged! Thanks for working on this ;)

**Pull request merged**
