### PR TITLE
Fix issue #67: fix instance call

### PR DESCRIPTION
**Pull request by xow**
Fix for #67

### CODE REVIEW

**Comment by xow** [comment]
In my haste, I neglected to realise that 1) this is a bad idea and 2) this will break the plugin. Reworking patch

**Comment by xow** [comment]
Updated, solution should work

**Comment by kabalin** [comment]
Thanks for commit @xow  Can you please add  `filter_jwplayer:` prefix to the commit message (just makes things to look nicer when we merge feature repos to deployment branch)?

**Comment by kabalin** [comment]
Thanks @xow

**Pull request merged**
